version: '3'

services:
  fronted:
    build: ./frontend
    restart: always
    ports:
#      Прокидывание порта
      - '3000:3000'
    volumes:
#      Это прокидывание томов и чтобы не бралась из папки node_modules
      - /app/node_modules
      - ./frontend:/app

  api:
    build: ./api
    restart: always
    ports:
      - '5555:5000'
#      Это что штука означает что мы сперва запустим контейнер mysql
    depends_on:
      - mysql
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PORT: '3306'
      MYSQL_PASSWORD: password
      MYSQL_DB: time_db

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'

# Это прокидвание данных на сам докер чтобы сохранять данные из БД
volumes:
   mysql_data: